# 安装Node.js
FROM node:latest

# 创建工作目录
WORKDIR /app

# 将node_modules添加到工作目录
COPY package*.json .
RUN npm install -g npm@9.6.7
RUN npm install

# 将所有文件复制到工作目录
COPY . .

# 编译前端项目
RUN npm run build

# 产生静态文件
FROM nginx:stable-alpine
COPY --from=0 /app/dist /usr/share/nginx/html/
COPY nginx.conf.template /etc/nginx/conf.d/

ENV CES_ADMIN_PORT=80 \
    CES_SERVER_NAME=ces_admin_server

LABEL maintainer="Zexin Feng <fengzx2021@mail.sustech.edu.cn>"
COPY nginx.conf.template /etc/nginx/conf.d/nginx.conf.template
COPY docker-entrypoint.sh /
RUN  chmod 777 /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 88
CMD ["nginx","-g","daemon off;"]