# 安装Node.js
FROM node:latest

# 创建工作目录
WORKDIR /app

# 将node_modules添加到工作目录
COPY package*.json .
COPY index.html .
COPY jsconfig.json .
COPY vite.config.js .
COPY src ./src
COPY public ./public
RUN npm install -g npm@9.6.7
RUN npm install

# 编译前端项目
RUN npm run build

# 产生静态文件
FROM --platform=$TARGETPLATFORM nginx:stable-alpine
COPY --from=0 /app/dist /usr/share/nginx/html/
COPY nginx.conf.template /etc/nginx/conf.d/

ENV CES_PORT=80 \
    CES_SERVER_NAME=ces_server

LABEL maintainer="Best-effort-team"
COPY nginx.conf.template /etc/nginx/conf.d/nginx.conf.template
COPY docker-entrypoint.sh /
RUN  chmod 777 /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx","-g","daemon off;"]